movies/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:movie_id>/", views.movie_detail, name="movie_detail"),
    path('actor/<int:actor_id>/', views.actor_detail, name='actor_detail'),
    path("your_name/", views.get_name, name="get_name"),
        path('logout/', views.logout_view, name='logout'),
    ]

mymovies/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

movies/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class Genre(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Job(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Person(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=200)
    overview = models.TextField()
    release_date = models.DateTimeField(blank=True)
    running_time = models.IntegerField(blank=True)
    budget = models.IntegerField(blank=True)
    tmdb_id = models.IntegerField(blank=True, unique=True, null=True)
    revenue = models.IntegerField(blank=True)
    poster_path = models.URLField(blank=True)
    genres = models.ManyToManyField(Genre)
    credits = models.ManyToManyField(Person, through="MovieCredit")

    def __str__(self):
        return self.title + ' ' + str(self.release_date.year)

class MovieCredit(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)

class MovieReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    review = models.TextField(blank=True)

    def __str__(self):
        return f"Review by {self.user.username} for {self.movie.title}"

movies/forms.py
from django import forms
from .models import MovieReview

class NameForm(forms.Form):
    your_name = forms.CharField(label="Nombre", max_length=100, help_text="100 car. máximo", 
                                    error_messages={"required": "El nombre es obligatorio"},
                                    widget=forms.Textarea(attrs={"class":"text-gray-400", "rows": 3, "cols": 60}))

class MovieReviewForm(forms.ModelForm):
    rating = forms.ChoiceField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')],
                                label='Rating')

    class Meta:
        model = MovieReview
        fields = ['rating', 'review']

movies/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from movies.models import Movie
from .forms import NameForm
from django.contrib.auth import authenticate, login, logout
from .forms import MovieReviewForm
from django.shortcuts import render, get_object_or_404
from django.db.models import Avg
import requests

# Create your views here.


def index(request):
    movies = Movie.objects.all()
    context = {'movie_list': movies}
    return render(request, "index.html", context=context)


def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    
    if request.method == 'POST':
        form = MovieReviewForm(request.POST)
        if form.is_valid():
            # Guardar el formulario en la base de datos
            review = form.save(commit=False)
            review.movie = movie
            review.user = request.user  # Asignar el usuario actual
            review.save()
            return HttpResponseRedirect(request.path)  # Redirigir a la misma página después de guardar
    else:
        form = MovieReviewForm()

    # Obtener todas las revisiones de la película
    reviews = movie.moviereview_set.all()
    
    # Calcular el promedio de las calificaciones
    average_rating = reviews.aggregate(Avg('rating'))['rating__avg']
    
    context = {'movie': movie, 'form': form, 'average_rating': average_rating}
    return render(request, 'movie_detail.html', context)
    
def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            print(form.cleaned_data)
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return render(request, "name_ok.html", {"form": form})
        else:
            return render(request, "name_ok.html", {"form": form})
    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, "name.html", {"form": form})
    
def actor_detail(request, actor_id):
    # Llama a la API de TMDB para obtener los detalles del actor
    api_key = '2b051c085b7a2d13993afe71ae5c5165'
    url = f'https://api.themoviedb.org/3/person/{actor_id}?api_key={api_key}&language=es'
    response = requests.get(url)
    actor = response.json()

    # Puedes agregar más lógica aquí para manejar errores, etc.
    context = {
        'actor': actor,
    }
    return render(request, 'actor_detail.html', context)
    
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
   

movies/templates/actor_detail.html
{% extends "base.html" %}

{% block article %}
<article class="container mx-auto px-4 py-8">
    {% if actor %}
        <div class="flex flex-col lg:flex-row h-[24rem] lg:h-[32rem] bg-gray-200 my-4 rounded-lg overflow-hidden shadow-lg">
            <div class="lg:w-1/3">
                <img class="w-full h-full object-cover hover:scale-105 transition-transform duration-300" src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{ actor.profile_path }}" alt="{{ actor.name }}">
            </div>
            <div class="p-6 flex flex-col justify-between lg:w-2/3">
                <div>
                    <h1 class="mt-2 font-bold text-4xl lg:text-5xl">{{ actor.name }}</h1>
                    <h2 class="font-semibold mt-4 text-lg">Biografía:</h2>
                    <p>{{ actor.biography }}</p>
                    <h2 class="font-semibold mt-4 text-lg">Fecha de nacimiento:</h2>
                    <p>{{ actor.birthday }}</p>
                    <h2 class="font-semibold mt-4 text-lg">Lugar de nacimiento:</h2>
                    <p>{{ actor.place_of_birth }}</p>
                    <h2 class="font-semibold mt-4 text-lg">Películas:</h2>
                    <ul>
                        {% for movie in actor.known_for %}
                            <li>{{ movie.title }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    {% else %}
        <p class="text-red-500">No se pudo cargar la información del actor.</p>
    {% endif %}
</article>
{% endblock article %}

movies/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Página de Ejemplo</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://unpkg.com/htmx.org@1.9.12" integrity="sha384-ujb1lZYygJmzgSwoxRggbCHcjc0rB2XoQrxeTUQyRjrOnlCoYta87iKBWq3EsdM2" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>
    <script>
        document.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        });
    </script>
</head>
<body class="bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100">
    <header class="h-16 bg-blue-600 text-white flex items-center justify-between px-6">
        <a href="http://44.217.219.118:8000/movies/"><h1 class="font-bold text-2xl">My Movies</h1></a>
        <div>
            {% if user.is_authenticated %}
                <span class="mr-4">Bienvenido!, {{ user.username }}</span>
                <form method="POST" action="{% url 'logout' %}" class="inline">
                    {% csrf_token %}
                    <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Cerrar Sesión</button>
                </form>
            {% else %}
                <a href="{% url 'admin:login' %}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Iniciar Sesión</a>
            {% endif %}
        </div>
    </header>
    <main class="container mx-auto p-4">
        {% block article %}{% endblock %}
    </main>
    <footer class="bg-gray-800 text-white py-4 text-center">
        <p>My Movies</p>
        <p><a href="https://github.com/cesarinmoca/MyMovies" class="underline">GitHub Repository</a></p>
    </footer>
</body>
</html>

movies/templates/index.html
{% extends "base.html" %}

{% block article %}

{% if movie_list %}
    <div id="movie_list" class="flex flex-wrap justify-center gap-8">
        {% for movie in movie_list %}
            <div class="max-w-xs rounded overflow-hidden shadow-lg transition-transform duration-300 transform hover:scale-105">
                <img class="w-full" src="/static/movies/assets/img/{{ movie.title |slugify}}.jpg" alt="{{ movie.title }} poster">
                <div class="px-6 py-4">
                    <div class="font-bold text-xl mb-2">{{ movie.title }}</div>
                    <p class="text-gray-700 text-base">
                        {{ movie.release_date |date:"M. j, Y"}}
                    </p>
                </div>
                <div class="px-6 pt-4 pb-2">
                    <a href="/movies/{{ movie.id }}/" class="inline-block bg-blue-500 rounded-full px-3 py-1 text-sm font-semibold text-white mr-2 mb-2">Ver Detalles</a>
                </div>
            </div>
        {% endfor %}
    </div>
       
    <!--    
    <h1 class="font-bold mt-8">Lista de Películas:</h1>
    <ul class="list-disc list-inside">
        {% for movie in movie_list %}
            <li><a href="/movies/{{ movie.id }}/" class="text-blue-500">{{ movie.title }} ({{ movie.release_date |date:"Y"}})</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p class="text-red-500">No hay películas disponibles.</p>
    {% endif %}
    -->

{% endblock article %}

movies/templates/movie.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{movie.title}}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'movies/assets/css/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1> {{ movie.title }} ({{ movie.release_date|date:"Y" }}) </h1>   
        <p> {{ movie.overview }} </p>
        <!-- <img src="{% static 'movies/assets/img'|add:movie.poster_path %}" alt=""> -->
        <img src ="https://media.themoviedb.org/t/p/w600_and_h900_bestv2/{{movie.poster_path}}">
    </body>
</html>

movies/templates/movie_detail.html
{% extends "base.html" %}

{% block article %}
<article class="container mx-auto px-4 py-8">
    <div class="flex flex-col lg:flex-row h-[24rem] lg:h-[32rem] bg-gray-200 my-4 rounded-lg overflow-hidden shadow-lg">
        <div class="lg:w-1/3">
            <img class="w-full h-full object-cover hover:scale-105 transition-transform duration-300" src="/static/movies/assets/img/{{ movie.title |slugify}}.jpg" alt="{{ movie.title }}">
        </div>
        <div class="p-6 flex flex-col justify-between lg:w-2/3">
            <div>
                <h1 class="mt-2 font-bold text-4xl lg:text-5xl">{{ movie.title }}</h1>
                <div class="movie-info mt-4">
                    <h2 class="font-semibold text-lg">Fecha de lanzamiento: </h2>
                    <p>{{ movie.release_date }}</p>
                    
                    <h2 class="font-semibold mt-4 text-lg">Géneros:</h2>
                    <ul class="movie-genre">
                        {% for genre in movie.genres.all %}
                            <li class="text-base">{{ genre.name }}</li>
                        {% endfor %}
                    </ul>
                    
                    <h2 class="font-semibold mt-4 text-lg">Duración: </h2>
                    <p>{{ movie.running_time }} minutos</p>
                </div>
                <h1 class="font-semibold mt-6 text-lg lg:text-xl">Overview</h1>
                <p class="mt-2 text-base">{{ movie.overview }}</p>
                <h2 class="font-semibold mt-4 text-lg">Average Rating:</h2>
                {% if average_rating %}
                    <p>{{ average_rating }}</p>
                {% else %}
                    <p>No ratings yet.</p>
                {% endif %}
                <details class="mt-4">
                    <summary class="font-semibold text-lg">Detalles de producción</summary>
                    <p>Presupuesto: {{ movie.budget }}</p>
                    <p>Ingresos: {{ movie.revenue }}</p>
                </details>
            </div>
        </div>
    </div>

    <div class="mt-8">
        <h1 class="font-semibold text-lg">Top Billed Cast</h1>
        <div class="font-semibold mt-2 text-base">
            <details>
                <summary>Cast</summary>
                {% for credit in movie.moviecredit_set.all %}
                    <p><a href="{% url 'actor_detail' credit.person.id %}" class="text-blue-500 hover:underline">{{ credit.person.name }}</a> - {{ credit.job.name }}</p>
                {% endfor %}
            </details>
        </div>
    </div>

    <h1 class="font-semibold text-lg mt-8">Reviews</h1>
    <div class="reviews">
        {% for review in movie.moviereview_set.all %}
            <div class="bg-gray-200 rounded-lg overflow-hidden shadow-lg my-4">
                <div class="p-4">
                    <h2 class="font-semibold text-lg">User: </h2>
                    <p>{{ review.user.username }}</p>
                    <h2 class="font-semibold text-lg">Rating: </h2>
                    <p>{{ review.rating }}</p>
                    <h2 class="font-semibold text-lg">Review: </h2>
                    <p>{{ review.review }}</p>
                </div>
            </div>
        {% empty %}
            <p>No reviews yet.</p>
        {% endfor %}
    </div>

    <h1 class="font-bold text-lg mt-8">Add Review</h1>
    <div class="add-review">
    <h1 class="font-bold text-lg mt-8">Add Review</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded-full mt-4 transition-colors duration-300">Submit</button>
    </form>
</div>

</article>
{% endblock article %}

movies/templates/review.html
<article id="review-{{ review.id }}">
  <div>
    {% if show_movie_title %}
    <h4 class="inline-block mr-2 italic text-xl">
      <a href="{% url 'movie-detail' review.movie.id %}#review-{{ review.id }}" class="hover:underline">
        {{ review.movie.title|title }}
      </a>
    </h4>
    {% endif %}
    <h5 class="inline-block mb-1">
      <span class="text-xl">{{ review.rating }}</span><span class="text-base">/100</span>
      <span class="text-sm text-gray-600">
        by <a href="{% url 'user-page' review.user.id %}" class="text-link">{{ review.user.username }}</a>
      </span>
      <span class="text-sm text-gray-600">
        on <time datetime="{{ review.date_time|date:'Y-m-d' }}">{{ review.date_time }}</time>
      </span>
    </h5>
  </div>
  {% if review.review %}
  {% comment %} The review migth be empty {% endcomment %}
  <p>{{ review.review }}</p>
  {% endif %}
</article>

movies/templates/review_form.html
{% if user.is_authenticated %}

<div class="mb-8 py-3 px-4 mx-auto rounded-md border bg-gray-100 border-gray-400">
  <form method="post" action="{% url 'nombre_de_la_vista_para_procesar_el_formulario' %}">
    {% csrf_token %}
    <fieldset>
      <legend class="text-lg mb-3 text-balance">Leave a review for &quot;{{ movie.title|title }}&quot;</legend>
      <div class="mb-2">
        <label for="rating" class="pr-2">Rating:</label>
        <input type="number" id="rating" name="rating" required min="0" max="100"
          class="py-1 px-2 rounded-md border-gray-400 focus:border-indigo-500">
      </div>
      <div class="mb-2">
        <label for="review">What do you think about this movie?</label>
        <textarea id="review" name="review" rows="3" placeholder="I liked the movie because..."
          class="py-1 px-2 block mt-1 min-h-8 w-full placeholder-gray-400 rounded-md border-gray-400 focus:border-indigo-500"></textarea>
      </div>
    </fieldset>
    <div class="mt-2">
      <button
        class="inline-block mx-auto py-1 px-3 text-zinc-50 bg-indigo-500 ease-out duration-200 hover:bg-indigo-700 rounded-md"
        type="submit">Save</button>
    </div>
  </form>
</div>

{% else %}

<p class="my-4">
  You need to be <a href="{% url 'login-user' %}" class="text-link">logged in</a> to leave a review.
</p>

{% endif %}